[package]
name = "tree-edit"
version = "0.1.0"
edition = "2021"
default-run = "tree-edit"

[dependencies]
rand = "0.8.4"
anyhow = "1.0"
clap = { version = "4.5.20", features = ["derive"] }
ignore = "0.4.23"
